models: 
  # - 'MLP'
  # - 'FCN'

  - 'TSERMamba'

  # - 'ConvTran'
  
  # - 'MiniROCKET'
  # - 'XGBoost'
  # - 'RandomForest'

# Training hyperparameters
criterion: 'MSELoss'
optimizer: 'Adam'
lr: 0.001
betas: [0.9, 0.999]
eps: 1e-8
num_epochs: 2000
patience: 50
batch_size: 32
batch_divisions: 1
runs: 1

datasets: 
  # - AppliancesEnergy
  # - FloodModeling3
  # - BenzeneConcentration
  # - BeijingPM10Quality

  # - FloodModeling1
  # - HouseholdPowerConsumption2
  # - LiveFuelMoistureContent
  # - BeijingPM25Quality

  # - Covid3Month
  # - HouseholdPowerConsumption1    
  # - FloodModeling2
  # - IEEEPPG

  # - NewsHeadlineSentiment
  # - NewsTitleSentiment
  - PPGDalia
  # - AustraliaRainfall
  
  # - BIDMC32SpO2
  # - BIDMC32HR
  # - BIDMC32RR

  # Outros datasets <----------------------------------------
  # - AcousticContaminationMadrid
  # - AluminiumConcentration
  # - BarCrawl6min
  # - BeijingIntAirportPM25Quality
  # - BenzeneConcentration

  # - BinanceCoinSentiment
  # - BitcoinSentiment
  # - BoronConcentration
  # - CalciumConcentration
  # - CardanoSentiment
  # - ChilledWaterPredictor
  # - CopperConcentration
  # - Covid19Andalusia
  # - DailyOilGasPrices
  # - DailyTemperatureLatitude

  # - DhakaHourlyAirQuality
  # - ElectricityPredictor
  # - ElectricMotorTemperature
  # - EthereumSentiment
  # - GasSensorArrayAcetone
  # - GasSensorArrayEthanol
  # - HotwaterPredictor
  # - IronConcentration
  # - LPGasMonitoringHomeActivity
  # - MadridPM10Quality

  # - MagnesiumConcentration
  # - ManganeseConcentration
  # - MethaneMonitoringHomeActivity
  # - MetroInterstateTrafficVolume
  # - NaturalGasPricesSentiment
  # - OccupancyDetectionLight
  # - ParkingBirmingham
  # - PhosphorusConcentration
  # - PotassiumConcentration
  # - PrecipitationAndalusia

  # - SierraNevadaMountainsSnow
  # - SodiumConcentration
  # - SolarRadiationAndalusia
  # - SteamPredictor
  # - SulphurConcentration
  # - TetuanEnergyConsumption
  # - VentilatorPressure
  # - WaveDataTension
  # - WindTurbinePower
  # - ZincConcentration